sepinf-inc/IPED

- README.md
Na linha "IPED (em contrução)", há um typo em "contrução".
> Typo em "contrução"

- iped-parsers/iped-parsers-impl/src/main/resources/dpf/mg/udi/gpinf/vcardparser/hcard-template.html
> Assume image/jpeg if no content type informed in vcard. Fixes #133

- iped-app/resources/config/profiles/en/blind/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/default/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/fastmode/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/forensic/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/pedo/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/triage/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/blind/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/default/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/fastmode/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/forensic/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/pedo/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/triage/conf/RegexConfig.txt
- iped-engine/src/main/java/br/gov/pf/iped/regex/BitcoinAddressValidatorService.java
Added some regex and validation for bitcoin keys and wallet formats.
The regexes were adapted from Zollner, Stephan & Choo, Kim-Kwang Raymond
& Le-Khac, Nhien-An. (2019). An Automated Live Forensic and Postmortem
Analysis tool for Bitcoin on Windows Systems. IEEE Access. PP.
10.1109/ACCESS.2019.2948774.
All these keys and addresses are encoded the same way as standard bitcoin addresses (Base58), so the validation was already implemented (except for the differend address headers).
In this PR, the following regexes were included:
WIF private key (5[a-km-zA-HJ-NP-Z1-9]{50})
WIF compressed private key ([KL][a-km-zA-HJ-NP-Z1-9]{51})
Encrypted private key (6P[a-km-zA-HJ-NP-Z1-9]{56})
Extended private key (xprv[a-km-zA-HJ-NP-Z1-9]{107,108})
Extended public key (xpub[a-km-zA-HJ-NP-Z1-9]{107,108}) …
> Add regexes for bitcoin related private Keys.

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ViewerController.java
I moved this fix to a separated branch so it can be merged before 3.18 release.
> Prevent best viewer bring-to-front when minimized or parent is hidden.

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/Manager.java
This pull request only makes sense if the described behavior in #397 was not intentional.
> Avoid starting too many Sleuthkit servers in robust mode. Fix #397

- iped-app/resources/config/conf/Log4j2ConfigurationFile.xml
The proposed change is an attempt to fix this issue.
I wasn't able to reproduce the problem after making the change in the Log4J configuration file (Log4j2ConfigurationFile.xml), but I am not sure if the issue is really gone.
The idea behind this change was to explicitly inform the package of PackageRegexpFilter class, so Log4j can always find it. 
Without this information, it tries to automatically find it, but it may fail depending on the order classes were built and loaded.
> An attempt to fix #471

- iped-app/resources/config/profiles/en/blind/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/default/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/fastmode/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/forensic/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/pedo/conf/RegexConfig.txt
- iped-app/resources/config/profiles/en/triage/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/blind/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/default/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/fastmode/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/forensic/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/pedo/conf/RegexConfig.txt
- iped-app/resources/config/profiles/pt-BR/triage/conf/RegexConfig.txt
According to [1], bitcoin SegWit addresses should be between 14 and 74
characters long, and contain only the following characters: [ac-hj-np-z02-9].
The current implementation works, as it has a more broad character set, and the false positives are excluded via checksum. But it doesn't hurt to be more specific.
Tested here with a bunch of files containing valid addresses, and all SegWit addresses were found correctly.
One more detail: it is possible to be even more specific, restricting the size of the address to only 42 or 62 characters. But the specification allows different sizes, that can be implemented in the future. So we chose allow all sizes in order to be future proof.
[1] https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
> Change Bitcoin SegWit address Regex to be more specific.

- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/util/MetadataUtil.java
@lfcnassif, testing other things here, I found that part of HEIC images had multiple values for "image:Width" and "image:Height".
This happens because drewnoakes/metadata-extractor library are getting wrong data for these fields in some cases.
An example:
```
HEIF Directory (4 tags)
[HEIF] Width - 512 pixels
[HEIF] Height - 512 pixels
```
While the correct dimension are:
```
Exif SubIFD Directory (29 tags)
[Exif SubIFD] Exif Image Width - 9490 pixels
[Exif SubIFD] Exif Image Height - 3782 pixels
```
The first directory (HEIF) is added to metadata without any prefix (just image:Width, not image:Heic:Width).
When I added the code to rename image related metadata (#522), I used `metadata.add()`, but I think `metadata.set()` would make more sense (these values should be unique anyway), and …
> Minor fix related to #522, avoiding multiple values.

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
Using in real cases, I found that in some situations the new button (#519) that clears all metadata filter was not clearing everything (items remained in the list with metadata keys).
> Sometimes clear button was not clearing everything. Fix related to #519

- iped-engine/src/main/java/gpinf/hashdb/HashDBTool.java
After the changes the importing tool (HashDBTool) accepts NSRL files with product codes that are not present in NSRLProd.txt (issue #611). 
As it is happening with too many lines in the RDS Version 2.73, I expect that it will be fixed in the provided files.
However it is better to handle this situation, as it may happen with fewer lines in future versions.
> Handle NSRL Product Code Inconsistencies

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/themes/DarkTheme.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/themes/ThemeManager.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/ui/controls/HoverButton.java
I found two minor details related to Dark mode #569, that could be improved:
- In the MetadataPanel, small buttons with icons have a special code to change their background/border when the mouse is over/pressed. It was not working properly when dark mode is selected. I moved the code to handle this from MetadataPanel to a new class (HoverButton), so it can be reused in other places. And this new implementation handles theme colors.
- Expand/collapse icon in trees (for non selected nodes) were hard to see in dark mode (black in a dark background). Because of Nimbus Look and Feel implementation, it was impossible to change it just setting UI properties (it would change other controls together). So I had to overwrite the implementation that paints these icons to make it theme aware.
> Dark mode adjustments

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/AutoCompletarColunas.java
After #18, property names are handled internally in English, but it is possible to define localized versions (used in user interface).
I guess it would be nice to include these localized versions in the auto complete feature (TAB in search field).
For example type "ca" and TAB would suggest "caminho".
Original version would still work, as queries can use both versions (original and localized).
> Included localized property names in auto-complete (TAB)

- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/shareazaparser/AlbumFolder.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/shareazaparser/LibraryFile.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/shareazaparser/LibraryFolder.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/shareazaparser/LibraryFolders.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/shareazaparser/ShareazaLibraryDatParser.java
Create a new column with the list of albums a file belongs to. If the
file is not in the filesystem (Library), only in albums, it will be
displayed with a blank path.
Only count childPornHashHit once per file.
> Display albums in new columns - Fix #708

- iped-api/src/main/java/iped3/search/IMarcadores.java
- iped-api/src/main/java/iped3/search/IMultiMarcadores.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GerenciadorMarcadores.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/Marcadores.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/MultiMarcadores.java
Closes #724.
I followed the current implementation (as it is done for bookmark comments), except when generating a report, in which shortcut keys were intentionally not copied to the report.
Added an unrelated very minor change, also in `GerenciadorMarcadores` class, to use a collator when sorting bookmarks by name.
For example, a bookmark named "Áudio" was going to the end of the list, while in the bookmark tree (left panel) it uses a more intuitive order (ignoring accents, with a collator).
> Save bookmarks shortcuts

- iped-api/src/main/java/iped3/util/ExtraProperties.java
- iped-api/src/main/java/iped3/util/MediaTypes.java
- iped-app/resources/config/conf/ParserConfig.xml
- iped-app/resources/config/profiles/triage/conf/ParserConfig.xml
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/datasource/UfedXmlReader.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ParsingTask.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/LibpffPSTParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/MSGParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/OutlookPSTParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/RFC822Parser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/util/MetadataUtil.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/MsgViewer.java
Closes #744, closes #745 
Add new properties Message:AttachmentCount and Message:IsEmailAttachment to EML, MSG, PST, OST and UFDR extracted emails. Removes old pst_attachment and pst_email_has_attachs properties.
> Attachment count and flag

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GalleryModel.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/DIETask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/VideoThumbTask.java
- iped-engine/src/main/java/gpinf/video/VideoThumbsMaker.java
This implements what was discussed in #763. 
Animated GIFs and APNGs support seems to be working fine and should be useful.
Testing with a couple of disk images from real cases I am working with, I found several images that I thought to be static images, including APNGs. 
Also find quite a few of these animated images in LED database.
@lfcnassif, I created a subcategory of images ("Animated Images"), but the current classification is somewhat based on the file location (Temporary Internet Images, Images in System Folders), and I found the result a bit confusing, as there could be animated images in these folders. 
I ended up rolling back, and didn't create any new category.
However, these animated images can be easily find using a filter by "image:AnimationFrames" property.
> Extract frames from animated images

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GalleryModel.java
Simple fix, as discussed in https://github.com/sepinf-inc/IPED/pull/767#issuecomment-955091808.
> Fix gallery to show document thumbs if available (related to #767).

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GerenciadorMarcadores.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTableListener.java
I noticed that copying the content of a cell using CTRL+C is not working (at least in my environment).
The whole line of the table is copied, which is the default behavior of JTable's.
It seems the default implementation runs after the customized one, overwriting clipboard content.
I believe this is a regression caused by #710.
As a solution, I added explicit calls to evt.consume() in the table key listener, whenever a key is actually processed by the application.
It solved the issue described here (selected cell content is now copied), and it is a good practice in general.
> Fix copying items table cell content using CTRL+C (in master)

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/App.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTableListener.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTableModel.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/util/AppSearchParams.java
This is a minor issue related to the dark theme #569.
When there are hits in the item name column, the highlighted part is visible (in yellow), but the rest of the name becomes hard to read (black on dark background).
> Fix font color in name column with hits in dark theme

- iped-api/src/main/java/iped3/util/MediaTypes.java
- iped-app/resources/config/conf/CarverConfig.xml
- iped-app/resources/config/conf/CustomSignatures.xml
- iped-app/resources/config/conf/scripts/RefineCategoryTask.js
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/datasource/SleuthkitReader.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/MimeTypesProcessingOrder.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/EmbeddedDiskProcessTask.java
- iped-engine/src/main/java/gpinf/dev/data/Item.java
Closes #102: add support for splitted E01/DD/VMDK images sending them to second processing queue.
EXX/VMDK segments are exported while processing the first queue and processed later together with first image segment. DD segments are exported later when processing second queue because they have no signature, being detected when first DD segment is processed, using its name and parent folder.
> Support for embedded and splitted E01/DD/VMDK images

- iped-app/pom.xml
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/Util.java
- iped-parsers/iped-parsers-impl/pom.xml
Upgrade embedded JRE to Liberica 11.0.13 x64 Full (includes JavaFX). Closes #827.
> #827 java11 upgrade

- iped-app/resources/config/conf/metadataTypes.txt
In the cases we have here, just setting **ufed:msgChildIds** to be an **Integer** in **metadataTypes.txt** solved the issue described in #848, but I am not sure if this is the best (or correct) way of handling this.
> Set ufed:msgChildIds to be an Integer (#848)

- iped-app/pom.xml
Fix #852. Merging should be done just after running some regression tests for other image file formats.
> fix #852 upgrade to imagemagick-7.1.0-q8-x64 to fix animated webp thumbs

- iped-app/resources/config/conf/CustomSignatures.xml
- iped-app/resources/config/conf/ParserConfig.xml
- iped-app/resources/config/profiles/triage/conf/ParserConfig.xml
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GalleryModel.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/DIETask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/VideoThumbTask.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/OCRParser.java
Applies the same solution used for Animated GIFs and APNGs, for HEIF/HEIC sequences (#854).
By the way, the test images that I have here were not being rendered by ImageMagick 6.
Perhaps it will work after upgrading to 7 (#855).
However, after this change, these images will be send to ImageMagick for OCR only (not for thumbnail creation or visualization).
> Handle HEIC/HEIF sequences as videos #854

- iped-app/src/main/java/dpf/sp/gpinf/indexer/IndexFiles.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/AppMain.java
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphFileWriter.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/MinIOTask.java
- iped-geo/src/main/java/dpf/mt/gpinf/mapas/googlemaps/MapaCanvasWebkit.java
- iped-geo/src/main/java/dpf/mt/gpinf/mapas/openstreet/MapaCanvasOpenStreet.java
- iped-geo/src/main/java/dpf/mt/gpinf/mapas/webkit/AbstractWebkitMapaCanvas.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/HtmlLinkViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/HtmlViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/util/DefaultPolicy.java
Closes #908: now a custom policy is used to block Internet access from viewers while allowing access from other modules, like the map tab. This black list policy eventually could be changed to a module white list policy in the future.
> #908 custom security policy

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ReferencesTableModel.java
I added a simple test to check if the item has no hash, avoiding the exception. 
Fix #939.
> Avoid an exception when the item does not have a hash value (#939)

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/Util.java
- iped-utils/src/main/java/dpf/sp/gpinf/indexer/util/IOUtil.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/EmailViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/MsgViewer.java
Closes #954: filter out invalid NTFS chars from attachment extension in EML/MSGViewers before extracting attachments to temp folder.
> #954 fix: clean attachment extension in Email viewers

- iped-api/src/main/java/iped3/ICaseData.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/Manager.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/Worker.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/AbstractTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/PythonTask.java
- iped-engine/src/main/java/gpinf/dev/data/CaseData.java
This closes #362 fixing some race conditions:
- when checking if processing queue is empty AND if there is no item being processed by workers;
- when checking if workers are idle to change processing queue;
A monitor lock was used and the old LinkedBlockingDeque for queues was replaced by a simple LinkedList.
> #362 better check empty queues and idle workers

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/datasource/UfedXmlReader.java
Closes #1035.
Sometimes base64 values are binary byte[], not printable strings, so I added check for some printable character ranges. If some decoded char is outside the allowed range, the value is kept base64 encoded and an _originalMetaKey_:format = base64 metadata is added to the item.
Let me know if we should add more allowed char ranges to the validation check.
> closes #1035: decode base64 strings, new metadata to flag base64 byte[]

- iped-api/src/main/java/iped3/configuration/IConfigurationDirectory.java
- iped-app/pom.xml
- iped-app/resources/config/conf/scripts/FaceRecognitionProcess.py
- iped-app/resources/config/conf/scripts/FaceRecognitionTask.py
- iped-app/resources/config/conf/scripts/NSFWNudityDetectTask.py
- iped-app/src/main/java/dpf/sp/gpinf/indexer/Main.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/AppMain.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/SimilarFacesFilterActions.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/config/Configuration.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/config/PluginConfig.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/PythonTask.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/inc/sepinf/python/PythonParser.java
When ready, this will close #1067: embed python+jep
A portable python-3.9.12 plus JEP-4.0.3 (and its dependencies) already compiled for Windows will be included, increasing IPED uncompressed size in about ~20MB. I compiled JEP against numpy-1.22.3, but later removed numpy because it uses ~60MB space. Installing numpy later is enough to make dependent modules to work fine, but maybe the same numpy version will be needed, I'll put a warning in the wiki.
I hope this will make running (c)python modules easier on Windows, since JEP won't need to be compiled anymore.
> #1067: Embed python+jep

- iped-engine/src/main/java/iped/engine/sleuthkit/SleuthkitClient.java
- iped-engine/src/main/java/iped/engine/sleuthkit/SleuthkitClientInputStream.java
Fixes #1187 & closes #1188:
- avoid reading old streams causing restarting loop after some crash
occurs;
- resume reading non problematic files from new process from their
previous position
- better code organization and synchronization usage
> fixes #1187 & closes #1188:

- iped-engine/src/main/java/iped/engine/hashdb/HashDBTool.java
I ran a few tests here, and it seems that the issue is gone.
Fixes #1242.
> Fix HashDB merge when importing hash sets

- iped-engine/src/main/java/iped/engine/task/index/IndexTask.java
Fix #1258. User just confirmed report creation from cmd line worked with the triggering case.
> fix #1258: don't load default types early to load them from source case

- iped-app/src/main/java/iped/app/ui/GalleryListener.java
- iped-app/src/main/java/iped/app/ui/GalleryTable.java
- iped-app/src/main/java/iped/app/ui/ResultTableListener.java
This implements #1299 and #1300.
When handling the arrow keys, only events with no modifiers (SHIFT, CTRL) are handled, as the goal was to make the navigation through gallery items easier. For selection, the current behavior was kept.
> #1299 1300 gallery events

- iped-app/src/main/java/iped/app/ui/parallelsorter/ParallelRowSorter.java
Fix #1353:
Adds an explicit synchronization to make parallel sorting changes visible to non calling threads.
@patrickdalla please test this on your Linux machine so we can be sure it is definitely fixed.
> fix #1353: add synchronization to make sorting visible to other threads

- iped-app/resources/config/conf/CategoriesConfig.json
@lfcnassif, I just noticed that mime types were swapped between Ares Galaxy and Shareaza in CategoriesConfig.json, in the PR #1367 I submitted (already merged).
I am sorry about that!
> Fix mimes that were swapped between Ares and Shareaza categories

- iped-api/src/main/java/iped/io/URLUtil.java
- iped-api/src/main/java/iped/localization/Messages.java
- iped-app/src/main/java/iped/app/processing/Main.java
- iped-app/src/main/java/iped/app/ui/AppMain.java
- iped-app/src/main/java/iped/app/ui/ReportDialog.java
- iped-app/src/main/java/iped/app/ui/ViewerController.java
- iped-engine/src/main/java/iped/engine/graph/GraphImportRunner.java
- iped-engine/src/main/java/iped/engine/graph/links/SearchLinksQueryProvider.java
- iped-engine/src/main/java/iped/engine/task/DocThumbTask.java
- iped-engine/src/main/java/iped/engine/task/regex/RegexValidator.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/external/ExternalParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/fork/ForkParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/PDFToImage.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/CADViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/util/DefaultPolicy.java
Opening a case from an unmapped network path (e.g. `\\myserver\case123`) wasn't working because of calls like the following one:
```
URL url = XyzClass.class.getProtectionDomain().getCodeSource().getLocation();
File file = new File(url.toURI());
```
The `URL` returned in the first line starts with something like `file://myserver/case123`.
The conversion to a `URI` (second line) fails with this kind of input.
I created an utility method that builds a new URL when it detects the "file" protocol and starting with "//", using "file:////" as the beginning.
All calls throughout the code were replaced, so the new utility method is used.
A project organization detail: I created the new method in `iped-api` subproject. Initially I placed it in `iped-utils`, but as there is localization-related …
> Handle Windows unmapped network paths (#1336)

- iped-engine/src/main/java/iped/engine/task/index/IndexItem.java
Fix #1409.
I ran a few tests here, and not resetting media type fixes the issue and doesn't seem to affect the "viewing process" (i.e. the preferred viewer still works).
> Do not reset media type (#1409)

- iped-engine/pom.xml
- iped-parsers/iped-parsers-impl/pom.xml
- iped-viewers/iped-viewers-impl/pom.xml
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/IcePDFViewer.java
- pom.xml
As discussed in #1426, if it is not possible to upgrade IcePDF because of its dependencies, maybe we could apply only the second commit (https://github.com/sepinf-inc/IPED/commit/c9244853c8196fc58f44349e0e0ad5b16c644493), which should help when using a UI scale != 1.0.
> PDF Rendering Quality (#1426)

- iped-app/resources/config/conf/VideoThumbsConfig.txt
- iped-engine/src/main/java/iped/engine/config/VideoThumbsConfig.java
- iped-engine/src/main/java/iped/engine/task/video/VideoThumbTask.java
- iped-engine/src/main/java/iped/engine/task/video/VideoThumbsMaker.java
Closes #1107.
@tc-wleite I was a bit confused about this formula:
`int frequency = (int) ((result.getVideoDuration() - 1000) * 0.00095 / (maxThumbs + 2));`
Not sure about the 95% and also about `(maxThumbs + 2)` also present in frameStep computation. But I tried to not change previous logic, it seems ok, please take a look.
Should we also add another optional configuration to attenuate the number of frames extracted, like applying square root to the number of frames?
> '#1107: new option to extract video frames at a fixed time interval

- iped-app/src/main/java/iped/app/timelinegraph/cache/TimeIndexedMap.java
The new memory month index needs the list of timeperiod cached entries sorted.
Some bars weren't showing when changing filters on high zoom in levels.
> BUG: the new memory month index needs the list of timeperiod cached entries sorted

- iped-app/resources/config/IPEDConfig.txt
- iped-engine/src/main/java/iped/engine/config/SplitLargeBinaryConfig.java
- iped-engine/src/main/java/iped/engine/task/FragmentLargeBinaryTask.java
- iped-engine/src/main/java/iped/engine/task/ParsingTask.java
- iped-engine/src/main/java/iped/engine/util/TextCache.java
Closes #1281 by splitting huge decoded texts before indexing.
For advanced users, it is still possible to disable FragmentLargeBinaryTask commenting it in TaskInstaller.xml, but I don't recommend it.
> #1281 aioobe indexing huge files

- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/css/whatsapp.css
- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/wachat-html-template.txt
Two very minor suggestions:
- Contact image (avatar) displayed in WhatsApp and Telegram HTMLs generated by the parsers could be a bit larger. Sometimes it contains an useful image, but it is too small (currently limited to 40x40 pixels). I suggest increasing it a bit, to 64. 
- There is a small detail in the CSS used by the WhatsApp and Telegram parsers that is keeping the background color used by WhatsApp chats in Telegram chats, in the contact name/picture. Example:
After the change:
> Small adjustments in WhatsApp and Telegram generated HTMLs

- iped-parsers/iped-parsers-impl/pom.xml
- iped-viewers/iped-viewers-impl/pom.xml
As discussed in #1530, removing the TIFF plugin (this PR) is an option to be evaluated. 
Another option would be chaging the plugin version to 3.8.2.
> Remove and force exclusion of TwelveMonkeys TIFF plugin (#1530)

- iped-engine/src/main/java/iped/engine/task/transcript/AbstractTranscriptTask.java
- iped-engine/src/main/java/iped/engine/task/transcript/GoogleTranscriptTask.java
- iped-engine/src/main/java/iped/engine/task/transcript/Wav2Vec2TranscriptTask.java
> Use internal Java code instead of FFmpeg to split long WAV audio files (#1267)

- iped-api/src/main/java/iped/properties/MediaTypes.java
- iped-engine/src/main/java/iped/engine/task/ImageThumbTask.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ocr/OCRParser.java
- iped-utils/src/main/java/iped/utils/ImageUtil.java
- iped-viewers/iped-viewers-impl/pom.xml
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/ImageViewer.java
- pom.xml
Closes #1531.
Also includes minor changes to improve: 
- The handling of files with multiple images is restricted to ICOs now, to avoid undesired side effects in other formats.
- The detection of "empty" images when the reading process is interrupted by an exception.
> Upgrade TwelveMonkeys to 3.9.4 (#1531)

- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
Kubernetes has a feature to check if the container is running that opens a connection to the service and closes it immediately after it is opened. So I made a change to detect this and logs it correctly.
> Allows k8s check state

- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
In case the current behavior was not intentional, this fixes #1644.
> Don't include external if phoneParsersToUse is set to internal for WhatsApp Business (#1644)

- iped-geo/src/main/java/iped/geo/parsers/GeofileParser.java
Set the id to the incremented virtualID and updates it in method return so sequential folders are not recursivelly stacked on inside the other.
> Corrects the bug of sequential folder stack in GeoFileParser

- iped-engine/src/main/java/iped/engine/task/die/DIETask.java
Currently, several messages (one per working thread) like below appear in the processing log when a report is generated (model file is not present).
```text
2023-05-29 19:22:02	[WARN]	[task.die.DIETask]			Invalid DIE database file: D:\XXXX\iped\models\rfdie.dat
2023-05-29 19:22:02	[WARN]	[task.die.DIETask]			Invalid DIE database file: D:\XXXX\iped\models\rfdie.dat
2023-05-29 19:22:02	[WARN]	[task.die.DIETask]			Invalid DIE database file: D:\XXXX\iped\models\rfdie.dat
2023-05-29 19:22:02	[WARN]	[task.die.DIETask]			Invalid DIE database file: D:\XXXX\iped\models\rfdie.dat
(...)
```
> Minor Fix in DIETask initialization to avoid multiple log messages when generating a report

- iped-app/src/main/java/iped/app/bootstrap/Bootstrap.java
Uses default windows SO certification store (that one that can be viewed on "Manage User Certificates" in Control Panel)  when executing on Windows.
> Uses default windows SO certification store when on windows.

- iped-app/src/main/java/iped/app/timelinegraph/IpedChartsPanel.java
- iped-app/src/main/java/iped/app/timelinegraph/datasets/IpedTimelineDatasetManager.java
Location of first call to load/create cache data was postponed to the first time the timeline tab is shown.
> Postpone timeline chart load

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/tor/TorTcParser.java
Timestamp string representations inside carved Tor TC entries are in UTC timezone although not informed at the end of the string, making IPED parse it as local time.
So, this PR appends a 'Z' char at the end of the string before adding it as metadata and set the metadata type for TORTC:TIME_CREATED as Date.
> Timestamp string representations inside carved Tor TC entries are in UTC

- iped-engine/src/main/java/iped/engine/task/ParsingTask.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/compress/SevenZipParser.java
Closes #1814.
@lfcnassif, in the code I used an auxiliary stream to check if the subitem content is equal to its parent. Maybe that could be done in a more concise way (using the same InputStream), but I was concerned about possible side effects, so I kept it the way it is.
> Detect and avoid a loop when the extracted item is equal its parent archive (#1814)

- iped-app/resources/config/conf/CarverConfig.xml
- iped-app/resources/config/conf/CategoriesConfig.json
- iped-app/resources/config/conf/CustomSignatures.xml
- iped-app/resources/config/conf/metadataTypes.txt
- iped-app/src/main/java/iped/app/ui/IconManager.java
- iped-carvers/iped-carvers-api/src/main/java/iped/carvers/api/CarverType.java
- iped-carvers/iped-carvers-impl/src/main/java/iped/carvers/standard/AbstractCarver.java
- iped-engine/src/main/java/iped/engine/task/carver/XMLCarverConfiguration.java
Closes #1816.
As discussed in https://github.com/sepinf-inc/IPED/issues/1816#issuecomment-1683029912, a new carving option (`stopOnNext header`) was added, to be used for SD files fo now, but possibly for other types in the future.
@lfcnassif, the new carving option is not essential, although I think it may be useful in some cases. As the carving process implementation is a critical part of the project, I tried to make the minimum amount of changes. If you think this may introduce some problem in the "regular" carving, we can remove this option. I ran two large tests, reprocessing two cases with many evidence files that I am currently working on. Compared with the previous processing, results matched as expected.
> Carver and file signature for Shareaza Download (SD) files (#1816)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/Util.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/css/whatsapp.css
- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/js/whatsapp.js
Closes #1840.
Closes #1842.
This should fix the link issue for audios and videos.
For other files types (like PDFs), there is a new JavaScript function named `openOther()`, but for now it only opens the file in the exported location (not in its original one). This will keep the current behavior for such files, and can be improved in the future.
Commits [d6fec93](https://github.com/sepinf-inc/IPED/commit/d6fec938c8ed4a7422095e5809a0154618a19cdc) and [8a7604f](https://github.com/sepinf-inc/IPED/commit/8a7604fe140b1cb21ac4f224593a4589b1683d12) are just minor formatting improvements.
> Review openIfExists (#1840) and some formatting enhancements (#1842)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ufed/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ufed/UFEDChatParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
There is a flag called ZREMOVED in the chatstorage database, if this flag is set to 1 the chat is deleted by the user. Another thing is that when importing messages from the UFED file they were not being exhibited as deleted in the chat HTML file. This fixes both cases.
> #1843 Better identification of deleted chats and messages

- iped-app/src/main/java/iped/app/ui/BookmarksManager.java
> Fix ALT bookmark removal key when CRTL and/or SHIFT are used (#1875)

- iped-engine/src/main/java/iped/engine/tika/SyncMetadata.java
- pom.xml
Some parsers load dates as Calendar objects,  but, although with correct timezone info loaded, doesn't have the other fields recomputed after this correct timezone is set. As the TIKA Metadata class implementation subsequently set the timezone to UTC to normalize all timezones, when the computeFields of calendar is called later, the original timezone info was lost, resulting in not applying the correct timezone offset correction.
This PR forces the computation of the fields before any subsequente Calendar operation.
> Metadata time zone flush to enforce timezone info

- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
> Always try DateFormats in the same order, to avoid timezone loss (#1879)

- iped-engine/src/main/java/iped/engine/task/transcript/VoskTranscriptTask.java
> Fix Vosk slow down after processing a lot of audios (#1909)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroid.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAAccount.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAContact.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAContactsExtractorIOS.java
This fixes a side effect of #1880.
Contacts read from iOS database already have "@s.whatsapp.net" suffix (at least in more recent databases).
In `WAContactsExtractorIOS`, the suffix was append again, resulting in IDs like `5511998877666@s.whatsapp.net@s.whatsapp.net`.
Before PR #1881, the `split("@")` removed the second "@s.whatsapp.net", but it shouldn't be added in the first place, if already present.
> Fix duplicated WhatsApp suffix (iOS)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
> Fix the query to get iOS WA chats

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
Fix #1921.
To reproduce this issue, it is possible to force the regular message extraction to fail (like it was before #1919).
Some media messages (image, video, audio etc.) will appear twice, if they have a deleted record and an active (non-deleted) one.
> Set MessageType before, so MediaHash is set for recovered WhatsApp iOS messages (#1921) 

- iped-engine/src/main/java/iped/engine/core/Manager.java
- iped-engine/src/main/java/iped/engine/task/HashTask.java
- iped-engine/src/main/java/iped/engine/task/regex/validator/cripto/EthereumAddressValidatorService.java
> #1849: Hash each digest algo in separated threads

- iped-utils/src/main/java/iped/utils/EmojiUtil.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/MetadataViewer.java
> Replace emojis characters by images in the metadata viewer (#1877)

- iped-app/src/main/java/iped/app/processing/ui/ProgressFrame.java
> New column with item's processing time in a task (#1904)

- iped-app/src/main/java/iped/app/timelinegraph/IpedChartPanel.java
- iped-app/src/main/java/iped/app/timelinegraph/IpedChartsPanel.java
to indicate if the filterSelection (and consequently app.getAppListener().updateFileListing()) should be called after filters remoaval. This should not be called on interface ClearFilterListener method clearFliter implementation.
> '#1929 Creates a clearFilter method on IpedChartsPanel with a parameter

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/PDFToThumb.java
> Swap image dimensions, if PDF page rotation is 90 or 270 (#1938)

- iped-engine/src/main/java/iped/engine/datasource/IPEDReader.java
- iped-engine/src/main/java/iped/engine/util/SaveStateThread.java
Fixes #1940.
The first commit (that makes `saveState()` synchronous) was enough to solve this particular issue.
However, I kept the changes I made in `SaveStateThread` class to handle asynchronous save calls in the correct order, as processing the save requests not in their original order may lead to other hard-to-trace issues.
> Avoid concurrency problems that may cause items not being included in their bookmarks when generating multicases reports (#1940)

- iped-engine/src/main/java/iped/engine/task/ParsingTask.java
Fixes #1947.
I could not find where the parsed media type became only "application/".
Not sure if it is even possible, but maybe a external (TIKA) parser.
> Do not overwrite the mediaType if new parsed type is null (#1947)

- iped-engine/src/main/java/iped/engine/datasource/FolderTreeReader.java
- iped-utils/src/main/java/iped/utils/FileInputStreamFactory.java
- iped-utils/src/main/java/iped/utils/IOUtil.java
Fix #1861 using a simple approach to skip problematic files and folders, warning users on the Console.
> Overcome path with trailing spaces 2

- iped-app/src/main/java/iped/app/processing/ui/ProgressFrame.java
- iped-engine/src/main/java/iped/engine/core/Statistics.java
- iped-engine/src/main/java/iped/engine/task/ParsingTask.java
Fix #1950 and minor code/log related enhancements.
> Simplify times per parser control

- iped-engine/src/main/java/iped/engine/data/Item.java
- iped-engine/src/main/java/iped/engine/io/ZIPInputStreamFactory.java
- iped-engine/src/main/java/iped/engine/task/TempFileTask.java
- iped-utils/src/main/java/iped/utils/SeekableFileInputStream.java
Closes #1224, closes #1958 and fixes #1955.
Simply increasing buffers used to read files from UFDRs from 8K to 64K resulted in up to 3x speed up in TempFileTask and overall 10%-15% speed up in total processing time in a few UFDR evidences I tested.
> #1224 Optimization for UFDR and small files

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/browsers/chrome/ChromeSqliteParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/browsers/edge/EdgeWebCacheParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/browsers/firefox/FirefoxSqliteParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/browsers/safari/SafariPlistParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/browsers/safari/SafariSqliteParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/discord/json/DiscordAttachment.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/emule/KnownMetParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/emule/PartMetParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/jdbc/JDBCTableReader.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/shareaza/LibraryFile.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/sqlite/SQLite3DBParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/telegram/Message.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/ChildPornHashLookup.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroid.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Message.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ReportGenerator.java
Closes #1960.
Just minor memory optimizations and code enhancements describe in the issue.
EDIT: In some parsers, the memory usage is very low, so these changes don't make any practical difference. However, as parsers' code are sometimes used as references for future parsers, I changed all of them to use a similar logic regarding HashDB lookup related code.
> Minor memory optimizations (#1960)

- iped-engine/src/main/java/iped/engine/config/Configuration.java
Closes #1979 
Load config soon after object creation to avoid dependent code execution before it.
> Locale config loaded sooner

- iped-geo/src/main/java/iped/geo/impl/AppMapPanel.java
- iped-geo/src/main/java/iped/geo/impl/MapViewer.java
closes #1973 
syncselection method, that sends selection made in results table when map was not visible, wasn't filtering out non georeferenced items leading to exceptions being printed in App Log. This PR reimplements the method to filter them out.
> Map selection sync error

- iped-app/pom.xml
- iped-parsers/iped-parsers-impl/pom.xml
- pom.xml
Closes #1990.
Much more contacts are being decoded and search hits for common words on chats and instant messages increased.
> closes #1990: upgrade telegram decoder plugin, use jitpack artifacts

- iped-engine/src/main/java/iped/engine/datasource/IPEDReader.java
Fix #2037.
@lfcnassif, although the fix is simple, this part of the code is somewhat complex (and I am not very familiar with it).
So please take a closer and see if the proposed fix makes sense.
> Fix multicase report bookmarks (#2037)

- iped-app/src/main/java/iped/app/processing/ui/ProgressConsole.java
- iped-app/src/main/java/iped/app/processing/ui/ProgressFrame.java
- iped-engine/src/main/java/iped/engine/core/Manager.java
- iped-engine/src/main/java/iped/engine/datasource/ItemProducer.java
Fix #2064.
When calculating the estimated time to finish processing, it uses the "Total Volume", the "Processed Volume" and the "Elapsed Time".
The negative time happened in the final part of the processing, when the "Processed Volume" was greater than the "Total Volume".
It shouldn't happen (the "Processed Volume" should be always less than or equal to the "Total Volume"), but it was because the "Total Volume" used in the calculation may have an outdated value (present in the beginning of the processing, but later incremented). The "Total Volume" presented in GUI was correct (updated).
Information used came from two different sources:
- The ProgressFrame/Console query Statistics to get these values;
- The ProgressFrame/Console receives new values through property changed events.
I …
> Use a single source of info to estimate time to finish (#2064)

- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
When using a UFED XML report as DataSource, UfedXmlReader.java was trying to use the XML file itself as a root folder for files referenced inside de XML. It should use the folder containing the XML report instead.
> Use folder containing UFED XML report as root. Fix #2089

- iped-carvers/iped-carvers-impl/src/main/java/iped/carvers/custom/MOVCarver.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/MetadataUtil.java
Fixes #2110.
This was a tricky issue.
First, the provided file was carved as a video, but it was actually an audio file.
In `MetadataUtil`, it received both "audio:" and "video:" prefix because "Indexer-Content-Type" = "video/mp4" and
"Content-Type" = "audio/mp4".
In the code, checking if it's a video uses both properties ("Indexer-Content-Type" and "Content-Type"). If at least one of them starts with "video" it receives the "video:" prefix. Audio checks only the second property.
I kept this behavior (video check both properties), but changed the code to accept just a single prefix (among "video:", "audio:", "image:" and "pdf:"). This was enough to solve the issue.
I also refined the header signatures used by `MOVCarver`, so it handles "audio/mp4", so files like the provided one would be …
> Fix metadata error (#2110)

- iped-app/resources/config/conf/CustomSignatures.xml
- iped-carvers/iped-carvers-impl/src/main/java/iped/carvers/custom/MOVCarver.java
@lfcnassif, not setting the mime type while carving "ftypmp42" as you suggested seems much better.
I had to add a custom signature for "audio/mp4", as the default behavior was detecting these audios as videos.
I tested with a synthetic case (with few videos and audios merged with random bytes in a large binary block) and a real case (no "audio/mp4" files in that case, but many videos), and it behaved as expected.
Sorry for overlooking this!
> More robust audio detection in MOVCarver (#2110)

- iped-app/resources/config/profiles/forensic/conf/ParserConfig.xml
- iped-app/resources/config/profiles/pedo/conf/ParserConfig.xml
- iped-engine/src/main/java/iped/engine/config/ParsersConfig.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/usnjrnl/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/usnjrnl/UsnJrnlParser.java
- iped-parsers/iped-parsers-impl/src/test/java/iped/parsers/usnjrnl/AbstractPkgTest.java
- iped-parsers/iped-parsers-impl/src/test/java/iped/parsers/usnjrnl/UsnJrnlParserTest.java
> Usn reason timestamp

- iped-app/src/main/java/iped/app/ui/CaseSearcherFilter.java
- iped-engine/src/main/java/iped/engine/search/MultiSearchResult.java
Does not caches the union of bitmaps in a resulting bitmap, as the order of the filters applied in cache may not follow the order that is enforced by the filterer registration in filter manager.
This PR closes '#2251 and '#2252
> Does not caches the union of bitmaps in a resulting bitmap

- iped-app/resources/config/conf/CarverConfig.xml
- iped-app/resources/config/conf/CategoriesConfig.json
- iped-app/resources/config/conf/MakePreviewConfig.txt
- iped-app/resources/config/conf/ParserConfig.xml
- iped-app/resources/config/profiles/triage/conf/ParserConfig.xml
- iped-app/src/main/java/iped/app/ui/IconManager.java
- iped-carvers/iped-carvers-impl/src/main/java/iped/carvers/custom/ResumeDatEntryCarver.java
- iped-engine/src/main/java/iped/engine/core/QueuesProcessingOrder.java
- iped-engine/src/main/java/iped/engine/task/P2PBookmarker.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/bittorrent/BitTorrentResumeDatEntryParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/bittorrent/TorrentFileParser.java
Closes #2234.
I finished the code changes and successfully processed a case I am working on.
I am leaving it as draft so I can test with other cases.
> Carver and parser for torrent resume.dat entries (#2234)

- iped-app/src/main/java/iped/app/ui/TreeListener.java
- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
Closes #2264.
Please @aberenguel, when you have time, test this on the UFDR that triggered the issue you reported on #2264, thank you in advance!
> #2264: Fix UI freezing if navigate to parent fails and avoid duplicating replied messages in the case

- iped-api/src/main/java/iped/properties/ExtraProperties.java
- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
- iped-engine/src/main/java/iped/engine/graph/GraphTask.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/discord/DiscordParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/skype/SkypeParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/telegram/TelegramParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/threema/ThreemaParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
- iped-parsers/iped-parsers-impl/src/test/java/iped/parsers/telegram/TelegramParserTest.java
Closes #2011. This can have a big impact in case disk size and processing time when groups with many members and messages are decoded from IM applications.
I would like someone else to review this, since it will change the output of some chat decoders (Telegram, WhatsApp, Threema, Discord, Skype, UFDR imported chats).
@hauck-jvsh could you take a look after you return from vacation?
@aberenguel, could you test this with the UFDR you mentioned on #2011?
> #2011: Use group identifier as Communication:To in group messages

- iped-engine/src/main/java/iped/engine/data/BitmapBookmarks.java
- iped-engine/src/main/java/iped/engine/data/MultiBitmapBookmarks.java
Properly invalidates internal unions cache after bookmark deletion and creation.
Closes #2311.
> Properly invalidates internal unions cache after bookmark

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroidNew.java
> WhatsApp Android Parser: Read CHAT and JID directly instead of CHAT_VIEW that was changed (#2326)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Message.java
> Review WhatsApp Message compareTo() to avoid "Comparison method violates its general contract" exceptions.

- iped-engine/src/main/java/iped/engine/task/similarity/ImageSimilarityTask.java
> Do not calculate image similarity features again, if already present (#2346)

- iped-app/src/main/java/iped/app/ui/GalleryCellEditor.java
- iped-app/src/main/java/iped/app/ui/GalleryCellRenderer.java
- iped-app/src/main/java/iped/app/ui/GalleryModel.java
- iped-app/src/main/java/iped/app/ui/GalleryTable.java
Closes #2344.
IndexReader/IndexSearcher.doc(id) calls are heavy, moving them from AWT thread to thread pool makes gallery cell rendering parallel and non AWT blocking on spinning disks.
@wladimirleite if you could confirm it improved rendering on spinning disk, I would appreciate very much. I also copied your improvements on other classes.
> #2344 gallery enhancement

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroid.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroidNew.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Message.java
The fix implemented by PR #2338 overlooked WhatsApp calls. 
They were incorrectly moved to end of the chat, as they don't have `sortId` (only `timeStamp`). 
This PR should fix this, merging messages with and without `sortId` based on their `timeStamp`.
It adds an additional step after `Collections.sort(messages)`, but it is O(n), in time and space, so there overhead is minimal.
> Fix sorting of WhatsApp messages (#2337 complement)

- iped-app/src/main/java/iped/app/ui/AppMain.java
- iped-app/src/main/java/iped/app/ui/splash/SplashScreenManager.java
> Warn the user about possibly corrupted JRE (#2357)

- iped-engine/src/main/java/iped/engine/task/transcript/RemoteTranscriptionTask.java
- iped-engine/src/main/java/iped/engine/task/transcript/Wav2Vec2TranscriptTask.java
> Disable audio transcription if initialization fails when creating reports (#2381)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
Fix #2337.
@lfcnassif, unfortunately I detected another issue related to #2337 in a real case, with a variety of conditions (backup merged, backups without the main database, databases without backups, multiple WA instances in a single device).
I just moved the call to `Message.sort()`, so now it will sort messages before generating the chat preview in all situations (before some cases were not covered).
> Sort before generating WA chat report (another fix related to #2337)

- iped-app/resources/config/conf/ImageThumbsConfig.txt
- iped-app/resources/scripts/tasks/FaceRecognitionTask.py
- iped-engine/src/main/java/iped/engine/config/ImageThumbTaskConfig.java
- iped-engine/src/main/java/iped/engine/task/ImageThumbTask.java
Create an image view for configured types (initially only HEIC) that are handle by the external graphics tool.
Closes #262.
I added this feature as an option inside ImageThumbTask, because it was much simpler in terms of code changes. And I regret not doing this before, as it was a small change that should help a lot viewing HEIC's in the analysis application.
I also included a minor change in FaceRecognitionTask, to use the item's view when available, which will allow recognizing faces in HEIC images.
It would also be possible to avoid conversion from HEIC during OCR, but OCR is done inside a parser, which runs before ImageThumbTask.
> Create an image view for configured types (#262)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Chat.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroid.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroidNew.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Message.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAContact.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/css/whatsapp.css
- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/wachat-html-template.txt
- iped-parsers/iped-parsers-impl/src/test/java/iped/parsers/whatsapp/WhatsAppParserTest.java
Closes #616.
I still need to run more tests ~(and fix unit tests)~, so I am leaving this as draft for now.
The implemented code create a new item named "WhatsApp Status - XXX" for each contact that has status updates, as discussed in the issue.
The key method is `expandBroadcastChat()`. 
If we want to merge the status updates with the contact's chat (i.e. place status+messages from a given contact in a single place), it should be straightforward, rewriting the method mentioned above.
> Handle WhatsApp status updates (#616) 

- iped-parsers/iped-parsers-impl/pom.xml
This PR fixes an issue caused by a transitive dependency in the iped-parsers-impl component.
The dependency com.webcohesion.ofx4j:ofx4j brings in org.reflections:reflections:0.9.10, which is outdated and triggers the error described in issue [#2518](https://github.com/sepinf-inc/IPED/discussions/2518).
The fix forces the use of a newer version of org.reflections:
`org.reflections:reflections:0.10.2`
This resolves the compatibility issue for the affected functionality.
- The fix was tested specifically for the functionality related to the reported error.
- I was not able to run the full build with all tests enabled, so further verification by maintainers is recommended.
This change should be reviewed and tested in a full build before merging to ensure no regressions occur.
> #2518 - Fix(iped-parsers-impl): force org.reflections to 0.10.2 to resolve transitive dependency issue

- iped-engine/src/main/java/iped/engine/task/ParsingTask.java
Fix #2598.
Alternative much simpler fix for #2598. Please @gmdalpian and @aberenguel, test if it is working as expected.
> fix #2598: enqueue subitems to don't run workers from parsing threads
