sepinf-inc/IPED

- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/detector/SQLiteContainerDetector.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/jdbc/SQLite3DBParser.java
- iped-utils/src/main/java/dpf/sp/gpinf/indexer/util/IOUtil.java
> Fix iped merging wal files

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/GalleryValue.java
> Copy item name in the gallery.

- .github/workflows/maven.yml
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/LibreOfficeViewer.java
> Java14 build

- iped-app/pom.xml
- iped-app/resources/config/profiles/en/blind/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/en/default/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/en/fastmode/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/en/forensic/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/en/pedo/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/en/triage/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/pt-BR/blind/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/pt-BR/default/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/pt-BR/fastmode/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/pt-BR/forensic/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/pt-BR/pedo/conf/DefaultFilters.txt
- iped-app/resources/config/profiles/pt-BR/triage/conf/DefaultFilters.txt
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/DIETask.java
- iped-engine/src/main/java/gpinf/die/RandomForestPredictor.java
- iped-engine/src/main/resources/iped-messages.properties
- iped-engine/src/main/resources/iped-messages_pt_BR.properties
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/util/ImageUtil.java
It can further improved (in terms of detection quality), but I believe the current status is good enough as a starting point. 
The model file also needs to be upated. @lfcnassif, I will send it directly to you.
> Die videos

- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/Message.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/TelegramParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/whatsappextractor/Message.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/util/LedHashes.java
- iped-parsers/iped-parsers-impl/src/main/resources/iped-parsers-messages.properties
- iped-parsers/iped-parsers-impl/src/main/resources/iped-parsers-messages_pt_BR.properties
Verify if the hashes of the telegram attachments are present on the LED KFF database.
> Hash look up

- iped-app/resources/config/conf/CustomSignatures.xml
- iped-app/resources/config/profiles/en/blind/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/default/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/fastmode/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/forensic/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/pedo/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/triage/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/blind/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/default/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/fastmode/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/forensic/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/pedo/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/triage/conf/CategoriesByTypeConfig.txt
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/jdbc/AbstractDBParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/jdbc/JDBCTableReader.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/jdbc/SQLite3TableReader.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/jdbc/TableReportGenerator.java
This possibly closes the issue #399, as this changes the behavior of the AbstractDBParser, I think it needs a detailed review.
> Sqlite parser

- iped-engine/src/main/java/br/gov/pf/iped/regex/PlacaRegexValidatorService.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/BCHAddressValidatorServiceTest.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/BitcoinAddressValidatorServiceTest.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/CreditCardRegexValidatorServiceTest.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/EthereumAddressValidatorServiceTest.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/PlacaRegexValidatorServiceTest.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/RIFRegexValidatorServiceTest.java
- iped-engine/src/test/java/br/gov/pf/iped/regex/RippleAddressValidatorServiceTest.java
I should have created an issue to add the rest of the regex tests. For future reference, I will do it that way. As there was little that would be added, I thought it would not be necessary, my mistake.
> Creating some unit tests for the regex package. Minor variables names

- iped-api/src/main/java/iped3/util/MediaTypes.java
- iped-app/resources/config/conf/CustomSignatures.xml
- iped-app/resources/config/profiles/en/blind/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/default/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/fastmode/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/forensic/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/pedo/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/en/triage/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/blind/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/default/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/fastmode/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/forensic/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/pedo/conf/CategoriesByTypeConfig.txt
- iped-app/resources/config/profiles/pt-BR/triage/conf/CategoriesByTypeConfig.txt
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/datasource/UfedXmlReader.java
- iped-engine/src/main/resources/iped-messages.properties
- iped-engine/src/main/resources/iped-messages_pt_BR.properties
I was not familiar with this part of the code (processing UFDR evidences), and it seems that there are many ways of implementing this feature. 
@lfcnassif, feel free to make any adjustment or to reject these changes.
> Extract UFDR Device Information 

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/QueryBuilder.java
> Fix #510 by locking the query parsing

- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/Contact.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/Extractor.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/TelegramParser.java
Fixes a null pointer exception when the decoder can't decode the message date
> Telegram parser

- iped-app/resources/config/conf/scripts/RefineCategoryTask.js
I submitted again, because the previous branch wasn't created from the master and included other unrelated changes.
> Fix to files with 0 bytes not included in Empty Files category. Fix #582

- iped-app/resources/config/profiles/blind/conf/ImageThumbsConfig.txt
- iped-app/resources/config/profiles/default/conf/ImageThumbsConfig.txt
- iped-app/resources/config/profiles/fastmode/conf/ImageThumbsConfig.txt
- iped-app/resources/config/profiles/forensic/conf/ImageThumbsConfig.txt
- iped-app/resources/config/profiles/pedo/conf/ImageThumbsConfig.txt
- iped-app/resources/config/profiles/triage/conf/ImageThumbsConfig.txt
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ImageThumbTask.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/util/GraphicsMagicConverter.java
> Externalize external conversion density and pixels in memory parameters

- iped-app/resources/config/conf/CustomSignatures.xml
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/RFC822Parser.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/EmailViewer.java
closes #651: detection and parsing for emls from outlook for imac
Waiting test from user with more eml samples.
> #651: detection and parsing for emls from outlook for imac

- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/util/MetadataUtil.java
> Avoid that renamed keys become duplicate (differ case only). Fix #522

- iped-app/resources/config/conf/metadataTypes.txt
- iped-app/resources/localization/iped-engine-messages.properties
- iped-app/resources/localization/iped-engine-messages_pt_BR.properties
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTableModel.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/RowComparator.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ViewerController.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/process/ProgressConsole.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/process/ProgressFrame.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/IndexItem.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/HTMLReportTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/QueryBuilder.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mt/gpinf/skype/parser/FormatUtil.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/AresParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/KnownMetParser.java
- iped-utils/src/main/java/dpf/sp/gpinf/indexer/util/LocalizedFormat.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/MetadataViewer.java
Closes #646.
After this is reviewed and merged, I will make the changes related to #649, to avoid conflicts in MetadataPanel.  
These changes were previously submitted in #647, but mixed with #649.
Now it contains only changes related to #646.
> Localized Number Formatting #646

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GalleryListener.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GerenciadorMarcadores.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MenuListener.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTableListener.java
A minor enhancement as explained in #710.
> Improve bookmarks shortcuts responsiveness using KeyPressed event.

- iped-app/resources/localization/iped-desktop-messages.properties
- iped-app/resources/localization/iped-desktop-messages_pt_BR.properties
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
- iped-utils/src/main/java/dpf/sp/gpinf/indexer/util/LocalizedFormat.java
Closes #649.
As there are a few minor changes included here, I tried to use more separate commits.
Just let me know if something isn't clear.
> Metadata Panel Enhancements

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/MinIOTask.java
As commented in #732 the minIO task was sending files that already exists again;
Files with zero length were being sent, this include a fix to not send this files;
> Bug fix: minIO task was sending files even when they already exists

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/AutoCompletarColunas.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
> Remove "bookmark" and "score" properties from metadata panel and autocomplete #761

- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ElasticSearchIndexTask.java
> Save the fragment number in the Elasticsearch index

- ReleaseNotes.txt
- iped-engine/pom.xml
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphImportRunner.java
> Upgrade neo4j to 3.5.30

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ColumnsManager.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/DynamicDuplicateFilter.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ExportIndexedTerms.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/GerenciadorMarcadores.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ImageSimilarityScorer.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTableRowSorter.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ResultTotalSizeCounter.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/RowComparator.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/TimelineResults.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/AttachmentSearcherImpl.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/analysis/StandardASCIIAnalyzer.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/IndexItem.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/SkipCommitedTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDSearcher.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDSource.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IndexerSimilarity.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/QueryBuilder.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/SimilarFacesSearch.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/DocValuesUtil.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/SlowCompositeReaderWrapper.java
- pom.xml
Work on #179 towards final Lucene 8 migration.
Difficulty here was a DocValues API change to an iterator like API, so a doc value is not random accessible anymore and should be accessed in index id order, resulting in logic changes in some modules. Furthermore DocValues instances can't be reused after the iteration.
I'll test this much more after returning from vacation in 2 weeks...
> #179 lucene7 upgrade

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/ExportIndexedTerms.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/analysis/CategoryTokenizer.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/analysis/FastASCIIFoldingFilter.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/analysis/LetterDigitTokenizer.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/analysis/StandardASCIIAnalyzer.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/Manager.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDSearcher.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDSource.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IndexerSimilarity.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/NoScoringCollector.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/SlowCompositeReaderWrapper.java
- pom.xml
> #179: upgrade to Lucene 8

- .github/workflows/maven.yml
- README.md
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/PythonTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/util/DirectMemory.java
- iped-geo/src/main/java/dpf/mt/gpinf/mapas/openstreet/MapaCanvasOpenStreet.java
- iped-geo/src/main/java/dpf/mt/gpinf/mapas/webkit/AbstractWebkitMapaCanvas.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/whatsappextractor/ExtractorIOS.java
- iped-viewers/pom.xml
- pom.xml
Closes #885: users will need java 11 to build or run the application since now.
> Java11 building

- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/util/MetadataUtil.java
If `image:Width` has a value, `image:Image Width` is simply removed.
Otherwise, `image:Image Width` is renamed to `image:Width`.
The same applies for `image:Image Height` -> `image:Height`.
Closes #898.
> #898: Rename (or remove) "Image Width" and "Image Height" properties.

- iped-app/resources/localization/iped-desktop-messages.properties
- iped-app/resources/localization/iped-desktop-messages_de_DE.properties
- iped-app/resources/localization/iped-desktop-messages_pt_BR.properties
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MenuClass.java
> #906: Group menu options related to layout and appearance.

- iped-parsers/iped-parsers-impl/pom.xml
- iped-parsers/iped-parsers-impl/src/main/java/dpf/ap/gpinf/telegramextractor/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/vcardparser/VCardParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/whatsappextractor/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/whatsappextractor/WhatsAppParser.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mt/gpinf/skype/parser/ReportGenerator.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/ufed/ReportGenerator.java
I think this will escape the HTML code;
closes #892 and closes #894
> #892 js injection

- iped-engine/src/main/java/br/gov/pf/iped/regex/BoletoRegexValidatorService.java
- iped-engine/src/main/java/br/gov/pf/iped/regex/CNHValidatorService.java
- iped-engine/src/main/java/br/gov/pf/iped/regex/CNPJRegexValidatorService.java
- iped-engine/src/main/java/br/gov/pf/iped/regex/CPFRegexValidatorService.java
- iped-engine/src/main/java/br/gov/pf/iped/regex/PisPasepRegexValidatorService.java
- iped-engine/src/main/java/br/gov/pf/iped/regex/PlacaRegexValidatorService.java
- iped-engine/src/main/java/br/gov/pf/iped/regex/TituloEleitorRegexValidatorService.java
> #926 fix regexes names;

- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/MetadataPanel.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/RowComparator.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/IndexItem.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ElasticSearchIndexTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/LoadIndexFields.java
Closes #837.
@hauck-jvsh please take a look if the ElasticSearchTask changes in ff847f2c790728d58251529e3d9f399e0000dea8 are enough, thanks.
> #837 index geopoints

- iped-engine/src/main/java/gpinf/hashdb/HashDBTool.java
> Add support to ProjectVIC data model 2.0 (#985)

- iped-app/src/main/java/br/gov/pf/labld/graph/desktop/AppGraphAnalytics.java
- iped-app/src/main/java/br/gov/pf/labld/graph/desktop/LoadGraphDatabaseWorker.java
- iped-app/src/main/java/br/gov/pf/labld/graph/links/AbstractSearchLinksQuery.java
- iped-engine/pom.xml
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphFileWriter.java
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphGenerator.java
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphImportRunner.java
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphService.java
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphServiceImpl.java
- iped-engine/src/main/java/br/gov/pf/labld/graph/GraphTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/datasource/IPEDReader.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/Manager.java
- iped-geo/pom.xml
This will close #889 when finished. Still need to fix #991 (also on 3.18.x)
> #889 neo4j 4.4.4 upgrade

- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/IcePDFViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/dpf/sp/gpinf/indexer/ui/fileViewer/frames/Viewer.java
> #989 fix rare ClassCastException while initializing UI

- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/whatsappextractor/ChatMerge.java
- iped-parsers/iped-parsers-impl/src/main/java/dpf/mg/udi/gpinf/whatsappextractor/WhatsAppParser.java
> #1003 Do not abort when there is an error in other msgstore file.

- iped-app/resources/localization/iped-desktop-messages.properties
- iped-app/resources/localization/iped-desktop-messages_de_DE.properties
- iped-app/resources/localization/iped-desktop-messages_pt_BR.properties
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/BookmarksManager.java
> Search for duplicate items using lucene search in some circumstances

- iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/detector/SQLiteContainerDetector.java
This adds two new names for the media table.
> Improves the detection of telegram databases

- iped-api/src/main/java/iped3/IIPEDSource.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/FileProcessor.java
- iped-app/src/main/java/dpf/sp/gpinf/indexer/desktop/TextParser.java
- iped-engine/pom.xml
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/lucene/NoScoringCollector.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/IndexItem.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/Statistics.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/IndexTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/SkipCommitedTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDMultiSource.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDSearcher.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/IPEDSource.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/QueryBuilder.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/SimilarDocumentSearch.java
- iped-engine/src/main/java/gpinf/dev/data/CaseData.java
Closes #1062. This is a sensitive change, I did a number of tests, I hope everything is fine.
> #1062 index parent child docs

- iped-app/resources/config/conf/MinIOConfig.txt
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/config/MinIOConfig.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ElasticSearchIndexTask.java
- iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/MinIOTask.java
> #1146 keep old content refs

- iped-engine/pom.xml
This revert the minio plugin version as it is happening random authentication errors.
Closes #1244
> Revert commit ce2255cdcb964bd564da02612132812172d34010

- iped-engine/src/main/java/iped/engine/lucene/analysis/AppAnalyzer.java
- iped-engine/src/main/java/iped/engine/lucene/analysis/StandardASCIIAnalyzer.java
- iped-engine/src/main/java/iped/engine/search/QueryBuilder.java
> #1246 #1247 fixes

- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/HexViewerPlus.java
fix hvpcombofield jdk 11 issues
fix number format exceptions
fix charset combo width
fix charset combo filter
fix isvalidnumber function
add isvalidhexstring function
fix #1290
> Hexviewerplus jdk11 fix

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ufed/UFEDChatParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ufed/UfedMessage.java
> Changes the metadatas from (Message-To, Message-From) to (Communication:To, Communication:From)

- iped-app/pom.xml
- iped-engine/src/main/java/iped/engine/datasource/SleuthkitReader.java
- pom.xml
> #1350 upgrade tsk 4.11.1 to patch 4

- iped-app/src/main/java/iped/app/ui/SimilarImagesFilterPanel.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/HexViewerPlus.java
I ended up fixing only the similar image panel issue.
For the hexadecimal viewer, just made a minor change in the default font size, which should minimize the glitch.
> Fix minor UI glitches #1365

- iped-viewers/iped-viewers-impl/pom.xml
> Upgrade ImageIO PSD to 3.8.2 and start using 3.8.3 for WEBP

- iped-utils/src/main/java/iped/utils/ImageUtil.java
- iped-viewers/iped-viewers-impl/pom.xml
> Render ICO files (#1383)

- iped-app/src/main/java/iped/app/ui/utils/UiScale.java
> Fix UI Scaling, always using US decimal format (#1368)

- iped-app/resources/config/conf/DefaultFilters.txt
- iped-app/src/main/java/iped/app/ui/FilterManager.java
- iped-utils/src/main/java/iped/utils/UTF8Properties.java
> #1392 fix user filters

- iped-app/resources/config/conf/CustomSignatures.xml
- iped-engine/src/main/java/iped/engine/config/CategoryConfig.java
- iped-engine/src/main/java/iped/engine/config/RegexTaskConfig.java
- iped-engine/src/main/java/iped/engine/core/Statistics.java
- iped-engine/src/main/java/iped/engine/data/Category.java
- iped-engine/src/main/java/iped/engine/data/IPEDSource.java
- iped-engine/src/main/java/iped/engine/graph/GraphConfiguration.java
- iped-engine/src/main/java/iped/engine/task/carver/XMLCarverConfiguration.java
Closes #897.
This is important to allow reproducing processing results when needed.
> #897 log all configurables

- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Discovery.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
> #1334 Log Stats in Transcription Cluster

- iped-app/src/main/java/iped/app/ui/App.java
- iped-app/src/main/java/iped/app/ui/FileProcessor.java
- iped-app/src/main/java/iped/app/ui/UICaseDataLoader.java
> Minor enhancements in wait dialog (#1413)

- iped-app/src/main/java/iped/app/ui/FileProcessor.java
- iped-app/src/main/java/iped/app/ui/MetadataPanel.java
- iped-app/src/main/java/iped/app/ui/UICaseDataLoader.java
This is a complement of #1414, fixing the code to show and hide the dialogBar ("Wait...") in the MetadataPanel, now the dialog is modal.
This should close #1413.
> Fix showing/hiding the dialogBar, now that is modal (#1413)

- iped-app/src/main/java/iped/app/ui/App.java
As explained in https://github.com/sepinf-inc/IPED/issues/1413#issuecomment-1302466273.
> Make dialogBar "document modal" not "application modal" (#1413)

- iped-api/src/main/java/iped/properties/ExtraProperties.java
- iped-app/resources/scripts/tasks/FaceRecognitionTask.py
- iped-engine/src/main/java/iped/engine/task/index/ElasticSearchIndexTask.java
This adds the number of faces to the extra attributes and export the faces as a nested item to opensearch.
Closes #1408
> #1408 export faces

- iped-engine/src/main/java/iped/engine/task/MinIOTask.java
> Do not update the IdInDataSource when uploading the preview

- iped-engine/src/main/java/iped/engine/datasource/SleuthkitReader.java
- iped-engine/src/main/java/iped/engine/task/FragmentLargeBinaryTask.java
- iped-engine/src/main/java/iped/engine/task/ParsingTask.java
> Fix FragmentLargeBinaryTask to check enabled flag (#1465)

- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/util/DefaultPolicy.java
@lfcnassif, as I changed a few things in my local environment attempting to use VisualVM before finding this, maybe something else is necessary.
Let me know if it works for you.
> Allow monitoring IPED's process using VisualVM (#1463)

- iped-app/src/main/java/iped/app/timelinegraph/IpedChartPanel.java
- iped-app/src/main/java/iped/app/timelinegraph/popups/TimelineFilterSelectionPopupMenu.java
Solves #1478 #1477 #1470 and #1471.
> Timeline interaction fixes

- iped-engine/src/main/java/iped/engine/core/Manager.java
- iped-engine/src/main/java/iped/engine/data/IPEDSource.java
Fix #1476.
@hauck-jvsh please test this with your triggering use case to check if it works, thanks.
> #1476 clear bookmarks of deleted items

- iped-engine/src/main/java/iped/engine/hashdb/HashDBTool.java
Hi @lfcnassif! 
Testing with the RDS V3 full databases today, I confirmed that they were imported as expected. However, I found out that the progress bar shows 100% since the beginning of the process, as the count of total records to be imported is wrongly estimated to be zero.
This pull request should fix this minor issue.
 
> Fix the progress bar for RDS V3 Full version (Complement of #1461)

- iped-app/src/main/java/iped/app/processing/ui/ProgressFrame.java
> Show processing progress in the system task bar (#1546)

- iped-app/src/main/java/iped/app/ui/FileProcessor.java
> Use dispose() instead of setVisible(false) (#1595)

- iped-engine/src/main/java/iped/engine/task/video/VideoThumbTask.java
> Set hasThumb when VideoThumbTask reuse view file (report processing) (#1614)

- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
Fix, the default protocol waits an accept message before send anything. So the message should be sent before check for a byte;
> Fix a bug introduced by the commit

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ocr/OCRParser.java
> Fix to avoid counting non-OCR characters in ocrCharCount (#1638)

- iped-app/src/main/java/iped/app/ui/splash/SplashScreenManager.java
> Avoid an exception when the splash screen is closed earlier (#1641)

- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2TranscriptTask.java
Sends a beacon each 60 seconds to keep the TCP connection alive.
> #1663 beacons

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ProtoBufDecoder.java
> Fix commit 19b3ec0, to handle iOS reactions properly (#1661)

- iped-parsers/iped-parsers-impl/src/main/resources/iped/parsers/whatsapp/css/whatsapp.css
> Fix balloon arrow position for WA special messages (Minor fix related to #1654)

- iped-app/src/main/java/iped/app/ui/App.java
- iped-geo/src/main/java/iped/geo/impl/MapViewer.java
- iped-geo/src/main/java/iped/geo/js/GetResultsJSWorker.java
- iped-geo/src/main/java/iped/geo/openstreet/MapCanvasOpenStreet.java
- iped-viewers/iped-viewers-api/src/main/java/iped/viewers/api/IMultiSearchResultProvider.java
Temporarily saves unprocessed tableModelEvent when map is hidden to be processed when it is shown
Closes #1710.
> Load and process map data only when it is visible

- iped-engine/src/main/java/iped/engine/task/carver/KnownMetCarveTask.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/emule/KnownMetDecoder.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/emule/PartMetParser.java
> #1730 make the known.met parser more resilient

- iped-app/src/main/java/iped/app/timelinegraph/IpedChartsPanel.java
- iped-app/src/main/java/iped/app/timelinegraph/IpedCombinedDomainXYPlot.java
- iped-app/src/main/java/iped/app/timelinegraph/datasets/IpedTimelineDataset.java
- iped-engine/src/main/java/iped/engine/task/index/ElasticSearchIndexTask.java
This replaces #1734 to target the 4.1.x branch. Thanks @patrickdalla!
I'll leave #1666 open until it is fixed on master.
> '#1666 Apply synchronization on timeline code to avoid concurrent access

- iped-app/src/main/java/iped/app/graph/GraphVizIpedResolver.java
- iped-engine/src/main/java/iped/engine/task/transcript/AbstractTranscriptTask.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/browsers/ie/IndexDatParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/registry/RegRipperParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/PDFToImage.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/util/Util.java
- iped-utils/src/main/java/iped/utils/IOUtil.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/CADViewer.java
> #1757 exit the while loop when an exception occurs;

- iped-engine/src/main/java/iped/engine/task/index/IndexItem.java
> Use sleuth.db location from the case (#1782)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/sqlite/SQLite3DBParser.java
> Ignore folders and items with different names in WAL search (#1791)

- iped-app/resources/config/conf/CustomSignatures.xml
> Add custom signatures for Matroska files (WEBM, MKV and MKA) (#1786)

- iped-engine/src/main/java/iped/engine/task/video/VideoThumbsMaker.java
> fix #1809: copy videos from long paths to local temp so mplayer works

- iped-utils/src/main/java/iped/utils/EmojiUtil.java
Fixes #1836.
@gfd2020, please give a try with you test case when you have some time.
> Do not replace emojis by images inside HTML tags (#1836)

- iped-engine/src/main/java/iped/engine/util/CLibrary.java
- iped-engine/src/main/java/iped/engine/util/Util.java
> #1846: use setenv in Linux to avoid problems reading APFS passwords in TSK

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WAContact.java
> More robust WAContact constructor (#1880)

- iped-engine/src/main/java/iped/engine/datasource/IPEDReader.java
- iped-engine/src/main/java/iped/engine/sleuthkit/SleuthkitClient.java
- iped-engine/src/main/java/iped/engine/task/EmbeddedDiskProcessTask.java
> #1870: check if SleuthkitClient instances were created in get()

- iped-engine/src/main/java/iped/engine/task/regex/RegexTask.java
> Fix regex processing with multiple hits for the same string (#1897)

- iped-app/pom.xml
> #1903 update tesseract and imagemagick

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroidNew.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorIOS.java
> Read messages at once, not per chat, to speed up WhatsApp parser (#1889)

- iped-engine/src/main/java/iped/engine/task/transcript/ProcessCrashedException.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Discovery.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2Service.java
- iped-engine/src/main/java/iped/engine/task/transcript/RemoteWav2Vec2TranscriptTask.java
- iped-engine/src/main/java/iped/engine/task/transcript/StartupException.java
- iped-engine/src/main/java/iped/engine/task/transcript/Wav2Vec2TranscriptTask.java
Fix #1942.
@hauck-jvsh, I'm still going to do tests, but I would appreciate your review, thanks.
> '#1942 send error 2 client if caused by startServer(), shutdown server process

- iped-engine/src/main/java/iped/engine/core/Manager.java
> Use the AmazonCorrettoCryptoProvider if it is available

- iped-app/src/main/java/iped/app/processing/ui/ProgressFrame.java
> Disable pause button until workers are created (#1993)

- iped-engine/src/main/java/iped/engine/hashdb/HashDBDataSource.java
- iped-engine/src/main/java/iped/engine/task/regex/RegexTask.java
> Ignore hashes and ids in the Regex search (#1988)

- iped-engine/src/main/java/iped/engine/task/P2PBookmarker.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/shareaza/ShareazaDownloadParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/shareaza/ShareazaLibraryDatParser.java
- iped-parsers/iped-parsers-impl/src/test/java/iped/parsers/shareaza/ShareazaLibraryDatParserTest.java
Complement to #1857.
1. Populate SHARED_HASHES property just if shared flag is true and totalDownloaded > 0.
2. Create automatic bookmark for shared files found in the case.
> #1857 complement

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/standard/StandardParser.java
> Minor optimization in StandardParser

- iped-engine/src/main/java/iped/engine/core/Manager.java
> Reset case finished flag only after basic checks (#2041)

- .github/workflows/maven.yml
Fix #2053: remote CI build and tests
> #2053 fix remote ci

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Message.java
> #2051: WhatsApp message thumbData - don't make recursion when file was not reopened

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/ufed/UFEDChatParser.java
> Fix a possible infinite loop (#2038)

- iped-app/resources/config/conf/TempFileTaskConfig.txt
- iped-engine/src/main/java/iped/engine/config/TempFileTaskConfig.java
- iped-engine/src/main/java/iped/engine/task/TempFileTask.java
> Make TempFileTask maximum file length configurable (#2100)

- iped-app/resources/config/IPEDConfig.txt
- iped-app/resources/config/profiles/fastmode/IPEDConfig.txt
- iped-app/resources/config/profiles/triage/IPEDConfig.txt
- iped-app/resources/scripts/tasks/SearchHardwareWallets.py
> Add a parameter in IPEDConfig.txt to allow enabling/disabling SearchHardwareWallets.py task (#1594)

- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
> Truncate excessive long names when reading a UFDR (#2107)

- iped-engine/src/main/java/iped/engine/task/carver/KnownMetCarveTask.java
> Check if at least one entry has a defined name and file size (#2116)

- iped-app/src/main/java/iped/app/bootstrap/Bootstrap.java
A minor adjustment related to #1712.
> Reduce the automatically set maximum for "-Xmx" from 32GB to 32500MB (complement of #1712) 

- iped-engine/src/main/java/iped/engine/data/BitmapBookmarks.java
> Minor fixes to BitmapBookmarks (#1632)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/telegram/Message.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/telegram/PostBoxCoding.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/telegram/TelegramParser.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/telegram/Util.java
> Do no link Telegram medias with empty or "zero length" hashes (#2157)

- iped-engine/src/main/java/iped/engine/hashdb/HashDBTool.java
> Sort by hash when reading NSRL databases to optimize hashes DB importing (#2160)

- iped-engine/src/main/java/iped/engine/lucene/analysis/AppAnalyzer.java
> Use actual (non localized) field names to check if it is a date (#2175)

- iped-engine/src/main/java/iped/engine/lucene/analysis/AppAnalyzer.java
A complement should fix #2175.
> Avoid NPE if fieldName is null (complement of #2175)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/Extractor.java
> Skip rows with NULL member, to avoid a NPE (#2190)

- iped-app/src/main/java/iped/app/bootstrap/Bootstrap.java
- iped-app/src/main/java/iped/app/ui/ViewerController.java
- iped-engine/src/main/java/iped/engine/task/DocThumbTask.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/util/LOExtractor.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/util/LibreOfficeFinder.java
> Extract LibreOffice (in Windows) even if "--nogui" was used (#2196)

- iped-engine/src/main/java/iped/engine/task/HTMLReportTask.java
> Check if the exported file exists to avoid broken links (#2203)

- iped-app/src/main/java/iped/app/ui/App.java
- iped-app/src/main/java/iped/app/ui/IconManager.java
- iped-app/src/main/java/iped/app/ui/utils/UiIconSize.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/components/HitsTable.java
> Increase the default row height (#2205)

- iped-app/src/main/java/iped/app/ui/ReportDialog.java
> Minor UI fix: adjust row height based on icon size in report dialog

- iped-engine/src/main/java/iped/engine/data/IPEDSource.java
> Count items in parent categories and add to children's totals (#2232)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ExtractorAndroidNew.java
> Fix WhatsApp call status (missed/refused were swapped)

- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
> Fix content of files from UFDR generated by PA 10.3

- iped-app/src/main/java/iped/app/ui/App.java
- iped-app/src/main/java/iped/app/ui/ViewerController.java
> #2290: fix loading the content when changing item and viewer tab

- pom.xml
> closes #2296: update Telegram decoder plugin

- iped-app/src/main/java/iped/app/ui/TextParser.java
- iped-engine/pom.xml
> '#1961: upgrade commons-compress to 1.27.1

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
Fix #2337 (for merged databases).
> Sort messages properly, after merging process (Additional fix to #2337)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/bittorrent/TorrentFileParser.java
> Check hashes parsed from torrents to avoid garbage in "linkedItems" (#2364)

- iped-app/src/main/java/iped/app/ui/GalleryTable.java
> Force the repaint of gallery single selected item (#2391)

- iped-app/resources/config/conf/AudioTranscriptConfig.txt
Updated comments to reflect the RemoteTranscriptionTask implementation class name
> Updated comments to reflect the RemoteTranscriptionTask class name

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
> Set created/modified dates based on first/ last messages dates (#2406)

- iped-app/src/main/java/iped/app/ui/App.java
Fix #2415.
Waiting user validation before merging.
> Fix #2415: Simplify code to avoid ClassCastException getting face thumb

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/sqlite/detector/SQLiteContainerDetector.java
> Fix WhatsApp Android SQLite detector based on table names (#2432)

- iped-app/resources/config/conf/Log4j2ConfigurationConsoleOnly.xml
- iped-app/resources/config/conf/Log4j2ConfigurationFile.xml
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/misc/OFXParser.java
> Increase OFX parser robustness (#2430)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/ReportGenerator.java
> Avoid an IOOBE when mime type read from WA DB has an invalid content (#2460)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/video/MP4Detector.java
- iped-parsers/iped-parsers-impl/src/main/resources/META-INF/services/org.apache.tika.detect.Detector
> #2356 Custom mp4 container detector

- iped-engine/src/main/java/iped/engine/task/TempFileTask.java
> Disable TempFileTask for report creation (#2463)

- iped-engine/src/main/java/iped/engine/data/MultiBitmapBookmarks.java
- iped-engine/src/main/java/iped/engine/data/MultiBookmarks.java
> Fix bookmarks load, checking the lastId instead of the total number of items (#2455)

- iped-engine/src/main/java/iped/engine/task/SignatureTask.java
- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/video/MP4Detector.java
- iped-utils/src/main/java/iped/utils/SimpleInputStreamFactory.java
A possible complement to close #2356.
> Exhaustive search for "vide", if MP4 has errors AND no video directory was found (Complement #2356)

- iped-app/src/main/java/iped/app/ui/App.java
- iped-engine/src/main/java/iped/engine/config/FileSystemConfig.java
- iped-engine/src/main/java/iped/engine/core/Manager.java
- iped-engine/src/main/java/iped/engine/datasource/IPEDReader.java
- iped-engine/src/main/java/iped/engine/datasource/SleuthkitReader.java
- iped-engine/src/main/java/iped/engine/sleuthkit/SleuthkitClient.java
- iped-engine/src/main/java/iped/engine/sleuthkit/SleuthkitInputStreamFactory.java
When finished, this will close #2450.
TODO: handle multicases scenarios.
> #2450 always respect robust image reading

- iped-app/resources/config/conf/FileSystemConfig.txt
- iped-engine/src/main/java/iped/engine/config/FileSystemConfig.java
> Adjust the default "numImageReaders" to 1/6 (#2480)

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
> Fix occasional ConcurrentModificationException's (#616)

- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/LibreOfficeViewer.java
> Take uiScale into account in LibreOffice viewer when taking screenshots (#2504)

- iped-engine/src/main/java/iped/engine/datasource/UfedXmlReader.java
> Handle UFDR "QuotedMessageData" entity (#2508)

- iped-engine/src/main/java/iped/engine/task/ImageThumbTask.java
- iped-utils/src/main/java/iped/utils/ImageUtil.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/ImageViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/TiffViewer.java
- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/util/ImageMetadataUtil.java
Closes #2468. 
Closes #2473. 
Closes #2477.
> Image related minor changes

- iped-parsers/iped-parsers-impl/src/main/java/iped/parsers/whatsapp/WhatsAppParser.java
> Create an "isEmpty" property for WhatsApp chats (#2506)

- iped-viewers/iped-viewers-api/src/main/java/iped/viewers/api/AbstractViewer.java
> Use rendering hints to improve viewer screenshots quality (#2502)

- iped-viewers/iped-viewers-impl/src/main/java/iped/viewers/IcePDFViewer.java
> Copy the whole displayed PDF page (#2500)

- iped-engine/src/main/java/iped/engine/config/AudioTranscriptConfig.java
> Clear AudioTranscript "remoteServiceAddress" (#2524)

- iped-app/src/main/java/iped/app/processing/CmdLineArgsImpl.java
> Check if the omitted output folder conflicts with an input (#2526)

- iped-app/resources/config/conf/CarverConfig.xml
- iped-carvers/iped-carvers-impl/src/main/java/iped/carvers/custom/SevenZipCarver.java
Closes #2557.
Could anyone review and test this?
> #2557 Carver for 7zip files

- iped-engine/src/main/java/iped/engine/search/QueryBuilder.java
> Fix handling Lucene minimum-should-match queries (#2578)

- iped-app/resources/config/conf/ProcessingPriorityConfig.txt
- iped-app/resources/config/profiles/fastmode/conf/ProcessingPriorityConfig.txt
- iped-app/resources/config/profiles/triage/conf/ProcessingPriorityConfig.txt
- iped-engine/src/main/java/iped/engine/config/Configuration.java
- iped-engine/src/main/java/iped/engine/config/ProcessingPriorityConfig.java
- iped-engine/src/main/java/iped/engine/core/Manager.java
- iped-engine/src/main/java/iped/engine/core/ProcessingQueues.java
- iped-engine/src/main/java/iped/engine/core/Worker.java
> Random Processing Queue (#2541)

- iped-engine/src/main/java/iped/engine/task/ImageThumbTask.java
Fix #2477.
See https://github.com/sepinf-inc/IPED/issues/2477#issuecomment-3140413324.
> Fix thumbnail orientation for images with "views" (fix related to #2477)

- iped-app/resources/root/help/Help_de-DE.htm
This little word mixup has been bugging me everytime I openend a case and I just needed to adjust the wording here ^^
> fix: update german translation
